version: 2.1

workflows:
  test-yoyo:
    jobs:
      - i-am-king-of-the-world

jobs:
  i-am-king-of-the-world:
    docker:
      - image: cimg/node:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  i-am-fake:
    steps:
      - run:
          name: List files
          command: ls -al
          