version: 2.1

jobs:
  whoami:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          command: |
            echo Start pipeline
            whoami
            pwd
  install:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache: # Caches dependencies with a cache key
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows
  list1:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - restore_cache: # Restores the cached dependency.
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: list files
          command: npm run list
  list2:
    docker:
      - image: ubuntu:latest
    steps:
      - restore_cache: # Restores the cached dependency.
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: list files
          command: |
            pwd
            ls -al
#...
workflows:
  build_and_test: # name of your workflow
    jobs:
      - whoami
      - install:
          requires:
            - whoami
      - list1:
          requires:
           - install # wait for build1 job to complete successfully before starting
           # see circleci.com/docs/2.0/workflows/ for more examples.
      - list2:
          requires:
           - install # wait for build1 job to complete successfully before starting
           # run build2 and build3 concurrently to save time.