version: 2.1

defaults: &yoyo
  docker:
    - image: cimg/node:17.0.1
  working_directory: ~/project

executors:
  my-executor:
    docker:
      - image: cimg/node:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/project

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >>
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  load_workspace:
    steps:
      - run: |
          cd ~ && pwd && ls -al
      - attach_workspace:
          at: ~/

jobs:
  install:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pwd
            npm install
      - run: |
          pwd
          ls -al
      - save_workspace
  step_one:
    executor: my-executor
    steps:
      - sayhello
      - load_workspace
      - run: npm test
  step_three:
    executor: my-executor
    steps:
      - sayhello:
          to: "myself"
      - load_workspace
      - run:
          command: |
            pwd
            ls -al
  summarize:
    executor: my-executor
    steps:
      - sayhello
      - load_workspace


workflows:
  lets_go:
    # triggers:
    #   - schedule:
    #       cron: "0,15,30,45,50,55 * * * 1-6"
    #       filters:
    #         branches:
    #           only: /^getting.*/
    jobs:
      - install
      - step_one:
          requires:
            - install
      - hold:
          type: approval
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
      - step_three:
          requires:
            - install
      - summarize:
          requires:
            - step_one
            - hold
            - step_three