version: 2.1

defaults: &yoyo
  docker:
    - image: cimg/node:17.0.1
  working_directory: ~/project

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >>
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  load_workspace:
    steps:
      - run: |
          cd ~ && pwd && ls -al
      - attach_workspace:
          at: ~/

jobs:
  install:
    <<: *yoyo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pwd
            npm install
      - run: |
          pwd
          ls -al
      - save_workspace
  step_one:
    <<: *yoyo
    steps:
      - sayhello
      - load_workspace
      - run: npm test
  step_three:
    <<: *yoyo
    steps:
      - sayhello:
          to: "myself"
      - load_workspace
      - run:
          command: |
            pwd
            ls -al
  summarize:
    <<: *yoyo
    steps:
      - sayhello
      - load_workspace


workflows:
  lets_go:
    jobs:
      - install
      - step_one:
          requires:
            - install
      - hold:
          type: approval
          requires:
            - install
      - step_three:
          requires:
            - install
      - summarize:
          requires:
            - step_one
            - hold
            - step_three